name: Test Simulator

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Verify Maestro installation
        run:
          maestro --version

      - name: Run Maestro Android Tests
        run: |
          APP_ID=$(cat android_appid.txt)
          echo "Running Maestro tests for Android appId=$APP_ID"
          maestro test .maestro/android-flow.yaml --format junit --output results-android.xml || true

      - uses: actions/upload-artifact@v4
        with:
          name: maestro-android-results
          path: results-android.xml